export const THEME_PRESETS = [
  {
    id: 'clean-saas',
    name: 'Clean SaaS',
    badge: '✨ Default',
    primaryColor: '#2563eb',
    accentColor: '#3b82f6',
    backgroundColor: '#FAFAF9',
    textColor: '#18181B',
    fontFamily: 'Outfit',
    borderRadius: '12px',
  },
  {
    id: 'modern-tech',
    name: 'Modern Tech',
    badge: '🔮 Cyber',
    primaryColor: '#6366f1',
    accentColor: '#818cf8',
    backgroundColor: '#0f172a',
    textColor: '#f8fafc',
    fontFamily: 'Outfit',
    borderRadius: '16px',
  },
  {
    id: 'corporate-sleek',
    name: 'Corporate Sleek',
    badge: '🏢 Executive',
    primaryColor: '#2563eb',
    accentColor: '#3b82f6',
    backgroundColor: '#0b1329',
    textColor: '#f1f5f9',
    fontFamily: 'Inter',
    borderRadius: '8px',
  },
  {
    id: 'startup-vibrant',
    name: 'Startup Vibrant',
    badge: '⚡ Electric',
    primaryColor: '#ec4899',
    accentColor: '#f43f5e',
    backgroundColor: '#111827',
    textColor: '#f9fafb',
    fontFamily: 'Plus Jakarta Sans',
    borderRadius: '20px',
  },
  {
    id: 'minimal-mono',
    name: 'Minimal Mono',
    badge: '🖤 Dark Minimal',
    primaryColor: '#f4f4f5',
    accentColor: '#a1a1aa',
    backgroundColor: '#09090b',
    textColor: '#fafafa',
    fontFamily: 'Poppins',
    borderRadius: '4px',
  },
  {
    id: 'creative-studio',
    name: 'Creative Studio',
    badge: '🎨 Design',
    primaryColor: '#8b5cf6',
    accentColor: '#d946ef',
    backgroundColor: '#130e2a',
    textColor: '#fdf4ff',
    fontFamily: 'Playfair Display',
    borderRadius: '24px',
  },
];
